version: 0.0
os: linux

files:
  - source: files/
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: "**"
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.sh
      runas: root
  AfterInstall:
    - location: scripts/webserver-start.sh
      runas: root
